baseURL = "https://senior-sigan.net/"
languageCode = "ru-RU"
title = "Ilya Siganov"
theme = "theme"

[taxonomies]
tag = "tags"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

#[[menu.main]]
#name = "About"
#url = "/about"
#weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

defaultContentLanguage = "ru"
hasCJKLanguage = false
enableEmoji = true
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]