title ="Ilya's digital garden"
url = ''
date_format = '%Y-%m-%d %H:%M:%S %z'

[assets]
src = 'content/assets'
dst = 'build/assets'

[markdown]
src = 'content'
dst = 'build'

[sass]
src = 'theme/styles'
style = 'compressed'
dst = 'build/app.css'

[scripts]
src = 'theme/scripts'
dst = 'build/scripts'

[layouts]
src = 'theme/layouts'

[graph]
dst = 'build/assets/graph.json'
