baseURL = "https://senior-sigan.net/"
languageCode = "ru-RU"
title = "Ilya Siganov"
theme = "theme"

defaultContentLanguage = "ru"
hasCJKLanguage = false
enableEmoji = true
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

googleAnalytics = "UA-113025618-1"

[taxonomies]
tag = "tags"
series = "series"

[params]
title = "blog.senior-sigan.net"
author = "Ilya Siganov"
email = "ilya.blan4@gmail.com"
tg_channel = "@senior_sigan_blog"
yandexWebMasterKey = "beb726920cbc64c2"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

#[[menu.main]]
#name = "About"
#url = "/about"
#weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "paraiso-dark"
    tabWidth = 4