baseURL = "https://blog.senior-sigan.net/"
languageCode = "ru"
title = "Ilya Siganov's blog"
theme = "terminal"
paginate = 10

defaultContentLanguage = "ru"
hasCJKLanguage = false
enableEmoji = true
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

googleAnalytics = "UA-113025618-1"
enableRobotsTXT = true

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[author]
name = "Ilya Siganov"

[taxonomies]
tag = "tags"
series = "series"

[params]
title = "blog.senior-sigan.net"
author = "Ilya Siganov"
email = "ilya.blan4@gmail.com"
tg_channel = "@senior_sigan_blog"
yandexWebMasterKey = "beb726920cbc64c2"
yandexMetrika = "34801205"
telegramDiscussSiteID = "TsEJ47sj"
googleVerificationId = "4z2ZC3wBB3v6UYDpgvaLobRiEJ-aN_apGHtUQDiRpZo"

# dir name of your main content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "posts"
# ["orange", "blue", "red", "green", "pink"]
themeColor = "orange"

# if you set this to 0, only submenu trigger will be visible
showMenuItems = 3

# show selector to switch language
showLanguageSelector = false

# set theme to full screen width
fullWidthTheme = false

# center theme with default width
centerTheme = false

[params.logo]
logoText = "Ilya Siganov's blog"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

#[[menu.main]]
#name = "About"
#url = "/about"
#weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "paraiso-dark"
    tabWidth = 4